### ISSUE TITLE
Apostrophe 's

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/orm-mapping-to-tables#33]
Correct the coloring- black, red- for the apostrophe s in last line. 
*********
The #save Method
In order to INSERT data into our songs table, we need to craft a SQL INSERT statement. Ideally, it would look something like this:

INSERT INTO songs (name, album)
VALUES <the given song's name>, <the given song's album>

**Comment by sgharms** [comment]
That highlighting is controlled by the syntax highlighting plugin. I changed the example words to use `snake_case` so that the highlighting is more predictable. Thanks.
