### ISSUE TITLE
The instructions are confusing

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/orm-mapping-to-tables#4]
Needs an overview in the desciprition to describe what you are building. Gotta give them a fighting chance of understanding the specs.
- [ ] Make a nested form, should also explain what models this form will be submitting
- [ ] explain their form should follow the name provided in the spec
- [ ] They don't know REST yet, so just tell them what route the form should submit to 
- [ ] Drop the "this is an exercise" bullet

Drop the Bonus

**Comment by jmburges** [comment]
also just read it over. It should feel like our other labs, not some weird obviously separately designed thing

**Comment by AnnJohn** [comment]
I'm sos orry. This wasn't supposed to be on this repo.

**Comment by AnnJohn** [comment]
(this is Joe)
